// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ProaktifArizaTahmini.DAL;

#nullable disable

namespace ProaktifArizaTahmini.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProaktifArizaTahmini.CORE.Entities.Disturbance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CfgFileData")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("Cfg_Dosyasi");

                    b.Property<string>("CfgFilePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Cfg_Dosya_Yolu");

                    b.Property<string>("ComtradeName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Comtrade_Dosya_Ismi");

                    b.Property<byte[]>("DatFileData")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Dat_Dosyasi");

                    b.Property<string>("DatFilePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Dat_Dosya_Yolu");

                    b.Property<DateTime>("FaultTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("Ariza_Saati");

                    b.Property<string>("FiderName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Fider_Adi");

                    b.Property<string>("HucreNo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Hucre_No");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("InstantDataPath")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Instant_Dosya_Yolu");

                    b.Property<int>("MyDataId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("RmsDataPath")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Rms_Dosya_Yolu");

                    b.Property<string>("RoleModel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Role_Model");

                    b.Property<bool>("Status")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("TmKvHucre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Tm_KV_Hucre");

                    b.Property<string>("TmNo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TM_No");

                    b.Property<string>("kV")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ID");

                    b.HasIndex("MyDataId");

                    b.ToTable("Disturbances");
                });

            modelBuilder.Entity("ProaktifArizaTahmini.CORE.Entities.HistoryOfChange", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("Degistirilme_Tarihi");

                    b.Property<int>("MyDataId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NewIP")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("New_IP");

                    b.Property<string>("OldIP")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Old_IP");

                    b.HasKey("ID");

                    b.HasIndex("MyDataId");

                    b.ToTable("HistoryOfChanges");
                });

            modelBuilder.Entity("ProaktifArizaTahmini.CORE.Entities.MyData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FiderName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Fider_Adi");

                    b.Property<string>("HucreNo")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("Hucre_No");

                    b.Property<string>("IP")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Path")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Port")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("RoleModel")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Role_Model");

                    b.Property<string>("TmKvHucre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Tm_kV_Hucre");

                    b.Property<string>("TmNo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("TM_No");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("kV")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("ID");

                    b.HasIndex("TmNo", "kV", "HucreNo")
                        .IsUnique()
                        .HasFilter("\"kV\" IS NOT NULL AND \"Hucre_No\" IS NOT NULL");

                    b.ToTable("MyDatas");
                });

            modelBuilder.Entity("ProaktifArizaTahmini.CORE.Entities.Disturbance", b =>
                {
                    b.HasOne("ProaktifArizaTahmini.CORE.Entities.MyData", "MyData")
                        .WithMany("Disturbances")
                        .HasForeignKey("MyDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyData");
                });

            modelBuilder.Entity("ProaktifArizaTahmini.CORE.Entities.HistoryOfChange", b =>
                {
                    b.HasOne("ProaktifArizaTahmini.CORE.Entities.MyData", "MyData")
                        .WithMany("HistoryOfChanges")
                        .HasForeignKey("MyDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyData");
                });

            modelBuilder.Entity("ProaktifArizaTahmini.CORE.Entities.MyData", b =>
                {
                    b.Navigation("Disturbances");

                    b.Navigation("HistoryOfChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
